### ISSUE TITLE
Do threads run application-wide or are they component-specific?

### ISSUE THREAD

**Issue by Unforgiven-wanda** [joltup/react-native-threads#14]
Hello,
Not an issue, mostly a question:
What I would like to know is if I start a thread in `componentA` like so:
```javascript
const thread = new Thread('worker.thread.js');
```
Then in `componentB` run the same file:
```javascript
const thread = new Thread('worker.thread.js');
```

Do I now have two threads running or a single one? Meaning do I have to terminate threads when unmouting my components or do all other components use the same thread, and so can I safely leave them?

Thank you.

**Comment by Traviskn** [comment]
Threads are not component specific, they keep running even if your component unmounts. In your example you have two independent threads running, even though they were created from the same file.  Threads only stop when you call `terminate()` on them, or if your whole application is closed. For this reason it is important to terminate threads in `componentWillUnmount`, otherwise you lose your reference to the thread and you won't be able to stop it.

**Comment by Unforgiven-wanda** [comment]
@Traviskn Thank you very much for the explanation. I had noticed memory consumption spikes (especially in debug for some reason) and since I have moved my thread to the global scope.
One last question: Does the thread stop once the user quits the app? Or does it keep running even after that? Should I stop it manually on my main component's `componentWillUnmount`?

**Comment by Traviskn** [comment]
Once the user quits the app the threads will terminate automatically
