### ISSUE TITLE
Android code replaces "/" with "_" in the thread path

### ISSUE THREAD

**Issue by Traviskn** [joltup/react-native-threads#20]
The README asks you to re-create the filepath under the android assets folder, so replacing the "/" can cause errors in some cases where you want to keep it

**Comment by radi-cho** [comment]
Yeah, I got the following error:
```
FATAL EXCEPTION: mqt_native_modules
                                                             Process: com.rsg.chess, PID: 6237
                                                             java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Unable to load script from assets 'threads/._index.thread.bundle'. Make sure your bundle is packaged correctly or you're running a packager server.
```

Can you suggest how to fix it? @Traviskn

**Comment by Traviskn** [comment]
Hi @radi-cho, can you show me your javascript code that is creating the thread? I suspect you may need to remove the leading `./` from your thread name. Apologies for the confusion, I probably need to update the example app and documentation

**Comment by Traviskn** [comment]
The code that is replacing `/` with `_` is in this file: https://github.com/joltup/react-native-threads/blob/master/android/src/main/java/com/reactlibrary/RNThreadModule.java#L61
I haven't gotten around to refactoring this code, but if removing this code that is changing the file path get's your app working we'd love to have a PR 😃

**Comment by radi-cho** [comment]
![image](https://user-images.githubusercontent.com/12954909/40879051-edf7a5f4-66a2-11e8-9899-6c4c6f8d79b9.png)
Hello! Sorry about that but I made my own thread solutin because I had no time to wait your fix or response. However I like this package pretty much and it's good that you still maintain it. If you have not enough time for managing project like this another users, _like me_ can stop use it and migrate to something else... So...

I want to recommend something: **If you want you can grant write access to [RSG Group](http://github.com/RSG-Group) and we will help with the maintenance** 😃 😄 😀

Also please try to help to the other waiting people:
- https://github.com/joltup/react-native-threads/issues/30
- https://github.com/joltup/react-native-threads/issues/29

**Comment by Traviskn** [comment]
`react-native-threads` is used in production every day in Jolt's applications. It works quite well for us and we maintain it primarily to meet the needs of our software.  It is challenging to prioritize the time to field support questions here in Github, especially when not enough details are provided (such as a code sample replicating the error). 

If users like yourself are able to find or create better solutions, that is great.  The fact that you were able to re-implement your own solution within 10 days is pretty impressive!  While we aren't wanting to give write access to developers outside of Jolt at this time, we are always open to pull requests.

**Comment by radi-cho** [comment]
Great, thanks!

**Comment by radi-cho** [comment]
Also can new developers join `joltup`?

**Comment by xiswar** [comment]
Hello, 

I had the same issue. For production the `./ `will get translated to `._` 

Pleas update the example app and the docs. For now it is not possible to have the `index.thread.bundle` file in a folder. It has to be in the rootDirectory.

**Comment by Traviskn** [comment]
The latest release fixes this issue, sorry it took me so long to get to it!  example app and docs should work as expected, particularly android in release mode
