### ISSUE TITLE
Doesn't work with haul

### ISSUE THREAD

**Issue by Morantron** [joltup/react-native-threads#28]
Hi!

I'm trying a project with [haul](https://github.com/callstack/haul) but I get 404s from haul dev server when it tries to fetch thread code.

Apparently in [this issue](https://github.com/callstack/haul/pull/358) @Traviskn made it work ( halp plz )

Any tips?

Thanks :pray:

**Comment by Traviskn** [comment]
Hi @Morantron, we configured haul to have multiple entry points in order to support thread bundles.

Here's an example that's close to what we did in our `webpack.haul.js`.  Some things that add complexity are that we have to alter the default config to not ignore node_modules, and we ended up needing to use a second config with a custom scripts to build for release mode.

For development mode, this is our main haul config:
```javascript
module.exports = (options, defaults) => {
  // Transform node_modules
  // See https://github.com/callstack/haul/issues/156
  defaults.module.rules[1].exclude = undefined;

  const entry = { [`index.${options.platform}`]: './index.js' };

  if (process.env.NODE_ENV === 'development') {
    entry['myworker.thread'] = './src/path/to/myworker.thread.js';
  }

  return {
    entry,
    output: {
      path: options.platform === 'ios'
        ? `${process.cwd()}/ios`
        : `${process.cwd()}/android/app/src/main/assets`,
      filename: '[name].bundle',
      publicPath: `http://localhost:${options.port}`,
    }
    module: { ...defaults.module },
  };
}
```

For building release thread bundles we use some custom npm scripts (you would run these before running the standard react native release build commands). In our `package.json`:
```json
  "scripts": {
    "bundleThreadAndroid": "NODE_ENV=production haul bundle --platform android --dev false --minify true --assets-dest ./android/app/src/main/assets --bundle-output ./android/app/src/main/assets/threads/myworker.thread.bundle --config ./thread.webpack.haul.js",
    "bundleThreadIos": "NODE_ENV=production haul bundle --platform ios --dev false --minify true --assets-dest ./ios --bundle-output ./ios/myworker.thread.jsbundle --config ./thread.webpack.haul.js",
  }
```
Notice our thread bundling scripts use a separate haul config file, `thread.webpack.haul.js`, which looks like this:

```javascript
module.exports = (options, defaults) => {
  // Transform node_modules
  // See https://github.com/callstack/haul/issues/156
  defaults.module.rules[1].exclude = undefined;

  return {
    entry: 'myworker.thread': './src/path/to/myworker.thread.js',
    output: {
      path: options.platform === 'ios'
        ? `${process.cwd()}/ios`
        : `${process.cwd()}/android/app/src/main/assets/threads/myworker.thread.bundle`,
      filename: 'myworker.thread.bundle',
      publicPath: `http://localhost:${options.port}`,
    },
    module: { ...defaults.module },
  };
}
```
I hope this is helpful, it ended up taking a bit of work to get the threads and haul working together 😅 
I should probably also mention that we have not yet upgraded to the latest version of Haul, (we're on 1.0.0-beta.12) so there could be issues if you're using a different version.

**Comment by Traviskn** [comment]
closing due to lack of response
