### ISSUE TITLE
Downloading files using threads in Background

### ISSUE THREAD

**Issue by vikas5914** [joltup/react-native-threads#32]
Hi,

I am creating a react native app, and I want to download some pdf files (Around 10, 2MB each) in the background. Do you think "react-native-threads" is a good solution for my use case? 

I know this is not an Issue, but I did not know where to ask. I am sorry about that.

**Comment by Traviskn** [comment]
Hi @vikas5914, I think it depends on what library you are using to download files.  In my apps I have used libraries like `react-native-fetch-blob`, and because native code handles actually downloading the files it does not block my JS thread and I have no need to use `react-native-threads`.  Using this library is best for cases where you need to perform a CPU intensive task in JavaScript.  File downloading is typically more of an IO bound task rather than a CPU bound one.

I hope that helps and makes sense!
